FROM python:3.10-slim
ENV TZ=Europe/Moscow
WORKDIR /app
RUN groupadd -r web \
    && useradd -d /app -r -g web web \
    && chown web:web -R /app
COPY .. /app
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt
USER web
CMD ["uvicorn", "/src/main:app", "--host", "0.0.0.0", "--port", "8080"]
